# Generated by Django 5.2.17 on 2026-09-26 20:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='accessibility',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='food',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='parking',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='transportation',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='what_to_bring',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
