# Generated by Django 5.2.17 on 2026-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpage_accessibility_eventpage_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='source_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='verification_status',
            field=models.CharField(choices=[('needs_confirmation', 'Needs detail confirmation'), ('confirmed', 'Details confirmed')], db_index=True, default='needs_confirmation', max_length=24),
        ),
    ]
