# Generated by Django 5.2.17 on 2026-09-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpage_review_notes_eventpage_source_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='map_url',
            field=models.URLField(blank=True),
        ),
    ]
