# Generated by Django 5.2.17 on 2026-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage_hero_image_homepage_hero_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='editor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='review_status',
            field=models.CharField(choices=[('needs_review', 'Needs owner/CEO review'), ('approved', 'Approved for publication')], default='needs_review', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='source_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='standardcontentpage',
            name='editor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standardcontentpage',
            name='review_status',
            field=models.CharField(choices=[('needs_review', 'Needs owner/CEO review'), ('approved', 'Approved for publication')], default='needs_review', max_length=20),
        ),
        migrations.AddField(
            model_name='standardcontentpage',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardcontentpage',
            name='source_reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
