# Generated by Django 5.2.17 on 2026-09-26 22:15

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage_editor_notes_homepage_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='community_pillar_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_pillar_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='future_direction_pillar_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='future_direction_pillar_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='practical_support_pillar_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='practical_support_pillar_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
