# Generated by Django 5.2.17 on 2026-09-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_community_pillar_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StandardContentPage',
        ),
    ]
