# Generated by Django 5.2.17 on 2026-09-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
